### ISSUE TITLE
issue in nodejs since version 1.5

### ISSUE THREAD

**Issue by craigklem** [bjornharrtell/jsts#344]
Have some code that worked in nodejs using jsts 1.4. It no longer works using jsts 1.5.or 1.6. The error I get is "TypeError: Gs.within is not a function" I also tried many different versions of node with no change, currently on latest 10.5. Is there something else I should be doing?

`var jsts = require('jsts');
var geometryFactory = new jsts.geom.GeometryFactory();

var coord = [
    new jsts.geom.Coordinate(-74181361, 40646457),
    new jsts.geom.Coordinate(-74142952, 40642256),
    new jsts.geom.Coordinate(-74096775, 40648182),
    new jsts.geom.Coordinate(-74050254, 40651080),
    new jsts.geom.Coordinate(-74050254, 40598313),
    new jsts.geom.Coordinate(-74135570, 40525935),
    new jsts.geom.Coordinate(-74194750, 40507371),
    new jsts.geom.Coordinate(-74256849, 40493110),
    new jsts.geom.Coordinate(-74258565, 40504793),
    new jsts.geom.Coordinate(-74254961, 40515952),
    new jsts.geom.Coordinate(-74246034, 40522738),
    new jsts.geom.Coordinate(-74249982, 40545667),
    new jsts.geom.Coordinate(-74229469, 40558612),
    new jsts.geom.Coordinate(-74216809, 40558482),
    new jsts.geom.Coordinate(-74206123, 40588830),
    new jsts.geom.Coordinate(-74199128, 40597270),
    new jsts.geom.Coordinate(-74200630, 40601897),
    new jsts.geom.Coordinate(-74203677, 40606328),
    new jsts.geom.Coordinate(-74203677, 40624311),
    new jsts.geom.Coordinate(-74200630, 40632747),
    new jsts.geom.Coordinate(-74185524, 40645936),
    new jsts.geom.Coordinate(-74181361, 40646457)
];
var linear = geometryFactory.createLinearRing(coord);
var poly = geometryFactory.createPolygon(linear);

var kPoint = geometryFactory.createPoint(new jsts.geom.Coordinate(-74176841, 40549765));

if (kPoint.within(poly)) {
    console.log("K Point within");
} else {
    console.log("K Point NOT within");
}

var pPoint = geometryFactory.createPoint(new jsts.geom.Coordinate(-74274401, 40504397));
if (pPoint.within(poly)) {
    console.log("Perth Point within");
} else {
    console.log("Perth Point NOT within");
}
`

**Comment by bjornharrtell** [comment]
Not expected, see no obvious explanation yet. The `within` method should be available in the ES5 build (https://github.com/bjornharrtell/jsts/blob/52a29edc5182b75f121d4a2f769eca19e44cb345/src/org/locationtech/jts/monkey.js#L75).

**Comment by bjornharrtell** [comment]
Reproduced also in browser and found the reason for the failure, `within` is not a member of `RelateOp` and the implementation of the `within` method should be as in upstream https://github.com/locationtech/jts/blob/7da8065738cac413b018dba2ddac4257c0ed63ca/modules/core/src/main/java/org/locationtech/jts/geom/Geometry.java#L840.
